### ISSUE TITLE
Any chance for update?

### ISSUE THREAD

**Issue by ChromiaCat** [Goinn/MultiplayerSongGrabber#1]
It shows this in the log:

> [18:29:22.408] [MultiplayerSongGrabber] System.TypeLoadException: Could not load type 'VRTK.UnityEventHelper.VRTK_Intera
ctableObject_UnityEvents' from assembly 'Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at MultiplayerSongGrabber.Downloader.ButtonInit()
   at MultiplayerSongGrabber.Downloader.OnSceneWasInitialized(Int32 buildIndex, String sceneName)
   at MelonLoader.MelonEvent`2.<>c__DisplayClass1_0.<Invoke>b__0(LemonAction`2 x) in D:\a\MelonLoader\MelonLoader\MelonL
oader\Melons\Events\MelonEvent.cs:line 192
   at MelonLoader.MelonEventBase`1.Invoke(Action`1 delegateInvoker) in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\E
vents\MelonEvent.cs:line 143

**Comment by Goinn** [comment]
The mod is currently not working with the open beta of the game. 
I will look into it in the coming days but no promises.

**Comment by WACOMalt** [comment]
Any luck? This mod is by far the most important one to me for this game. Thank you for your work!

**Comment by Goinn** [comment]
I have been quite busy with work recently. I hope to find some time to work on this mod and trahbin over the holidays.

**Comment by Goinn** [comment]
Short update I just got MelonLoader working on my side again since there seemed to be an issue with the installer some weeks ago and I can compile the mod again. That's the good news.
Now the bad news. I haven't played the game in quite a while and didn't notice the reworked UI. So this means that most of the references in the old code need to be replaced e.g. how events are called, button creation etc.

**Comment by Goinn** [comment]
Thanks to Bookdude we now have a working version of the mod again.
Please go to his page to get the newest version of the mod.
https://github.com/bookdude13/SRMultiplayerSongGrabber
